# Generated by Django 4.1.2 on 2024-02-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.BigAutoField(
                primary_key=True, serialize=False, verbose_name="course-id"
            ),
        ),
    ]
